### ISSUE TITLE
The app won't start - Error: A JNI Error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by abdullahmansoor727** [AshfaqAliZardariOfficial/AAZ-Android-Mirror-App#1]
Hello Ashfaq Ali Zardari!

### I am getting the error: A JNI Error has occurred, please check your installation and try again (Image attached)
<img width="307" alt="image" src="https://user-images.githubusercontent.com/31242849/178102152-7262dd8e-0df5-4791-933a-e894723b07a7.png">
### Followed by the error: A Java exception has occurred (Image attached)
<img width="185" alt="image" src="https://user-images.githubusercontent.com/31242849/178102178-72031e78-cd7d-409c-b027-681e93e77b89.png">

These errors pop up when I try to start the app. I have tried reinstalling the application. But the issue persists.

I am running Windows 11:
Edition	Windows 11 Pro
Version	21H2
Installed on	‎18/‎06/‎2022
OS build	22000.739
Experience	Windows Feature Experience Pack 1000.22000.739.0

### I also have Java Runtime Environment installed (Image attached)
<img width="369" alt="image" src="https://user-images.githubusercontent.com/31242849/178102321-459d7835-b615-4953-ad3e-24e0fd6cad56.png">

Please guide me, where I am going wrong?

**Comment by AshfaqAliZardariOfficial** [comment]
**Mr. Abdullah Mansoor,**

Thank you for your contribution to the **AAZ Mirror App** to make it better. We are very much complimented that you want like to use the **AAZ Mirror App**. 

This issue is related to **Java** (_A high-level programming language_).

Kindly properly install or reinstall Java to continue and use the **AAZ Mirror App**. If you need further assistance, kindly contact us.

If you may want immediate resolution, please contact us directly on **WhatsApp**. We would try our best to resolve your issue.

**Thank You!**

_Best regards,_
 **Ashfaq Ali Zardari, Full Stack Developer**
 +923152260604 (_WhatsApp only_)
 [ashfaqalizardariofficial@gmail.com](mailto:ashfaqalizardariofficial@gmail.com)
 [https://ashfaqalizardari.tk](https://ashfaqalizardari.tk)

**Comment by AshfaqAliZardariOfficial** [comment]
Kindly follow the video instruction to properly install Java and continue to use **AAP Mirror App**. 

 [How to Download and Install AAZ Mirror App properly.](https://youtu.be/UbKALqwD69Y)

 Thank you

**Comment by abdullahmansoor727** [comment]
Sure I'll reinstall Java and AAZ Mirror App then get back to you.

Thanks for the response.
